import { ChainConfig } from "./types";

export const USDT_CHAINS: ChainConfig[] = [
  {
    id: "ethereum-usdt",
    name: "Ethereum",
    token: "USDT",
    contractAddress: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    decimals: 6,
    rpcUrl: "https://eth.llamarpc.com",
    explorerUrl: "https://etherscan.io",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#627EEA",
    defillamaId: "tether",
  },
  {
    id: "tron-usdt",
    name: "Tron",
    token: "USDT",
    contractAddress: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
    decimals: 6,
    rpcUrl: "https://api.trongrid.io/jsonrpc",
    explorerUrl: "https://tronscan.org",
    explorerAddressPath: "/#/token20/",
    chainType: "tron",
    color: "#FF0013",
  },
  {
    id: "avalanche-usdt",
    name: "Avalanche",
    token: "USDT",
    contractAddress: "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7",
    decimals: 6,
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    explorerUrl: "https://snowscan.xyz",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#E84142",
  },
  {
    id: "solana-usdt",
    name: "Solana",
    token: "USDT",
    contractAddress: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    decimals: 6,
    rpcUrl: "https://api.mainnet-beta.solana.com",
    explorerUrl: "https://solscan.io",
    explorerAddressPath: "/token/",
    chainType: "solana",
    color: "#9945FF",
  },
  {
    id: "ton-usdt",
    name: "TON",
    token: "USDT",
    contractAddress: "EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs",
    decimals: 6,
    rpcUrl: "https://tonapi.io",
    explorerUrl: "https://tonviewer.com",
    explorerAddressPath: "/",
    chainType: "ton",
    color: "#0098EA",
  },
  {
    id: "near-usdt",
    name: "NEAR",
    token: "USDT",
    contractAddress: "usdt.tether-token.near",
    decimals: 6,
    rpcUrl: "https://rpc.mainnet.near.org",
    explorerUrl: "https://nearblocks.io",
    explorerAddressPath: "/address/",
    chainType: "near",
    color: "#00C08B",
  },
  {
    id: "celo-usdt",
    name: "Celo",
    token: "USDT",
    contractAddress: "0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e",
    decimals: 6,
    rpcUrl: "https://forno.celo.org",
    explorerUrl: "https://celoscan.io",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#FCFF52",
  },
  {
    id: "kava-usdt",
    name: "Kava",
    token: "USDT",
    contractAddress: "0x919C1c267BC06a7039e03fcc2eF738525769109c",
    decimals: 6,
    rpcUrl: "https://evm.kava.io",
    explorerUrl: "https://kavascan.com",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#FF564F",
  },
  {
    id: "kaia-usdt",
    name: "Kaia",
    token: "USDT",
    contractAddress: "0xd077a400968890eacc75cdc901f0356c943e4fdb",
    decimals: 6,
    rpcUrl: "https://public-en.node.kaia.io",
    explorerUrl: "https://kaiascope.com",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#3F51B5",
  },
  {
    id: "liquid-usdt",
    name: "Liquid",
    token: "USDT",
    contractAddress: "ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2",
    decimals: 8,
    rpcUrl: "https://blockstream.info/liquid/api",
    explorerUrl: "https://blockstream.info/liquid",
    explorerAddressPath: "/asset/",
    chainType: "liquid",
    color: "#009688",
  },
  {
    id: "polkadot-usdt",
    name: "Polkadot",
    token: "USDT",
    contractAddress: "1984",
    decimals: 6,
    rpcUrl: "https://polkadot-asset-hub-public-sidecar.parity-chains.parity.io",
    explorerUrl: "https://assethub-polkadot.subscan.io",
    explorerAddressPath: "/assets/",
    chainType: "polkadot",
    color: "#E6007A",
  },
  {
    id: "tezos-usdt",
    name: "Tezos",
    token: "USDT",
    contractAddress: "KT1XnTn74bUtxHfDtBmm2bGZAQfhPbvKWR8o",
    decimals: 6,
    rpcUrl: "https://api.tzkt.io",
    explorerUrl: "https://tzkt.io",
    explorerAddressPath: "/",
    chainType: "tezos",
    color: "#2C7DF7",
  },
  {
    id: "aptos-usdt",
    name: "Aptos",
    token: "USDT",
    contractAddress: "0xf73e887a8754f540ee6e1a93bdc6dde2af69fc7ca5de32013e89dd44244473cb",
    decimals: 6,
    rpcUrl: "https://fullnode.mainnet.aptoslabs.com/v1",
    explorerUrl: "https://explorer.aptoslabs.com",
    explorerAddressPath: "/account/",
    chainType: "aptos",
    color: "#4CA2FF",
  },
];

export const USDC_CHAINS: ChainConfig[] = [
  // --- EVM chains ---
  {
    id: "ethereum-usdc",
    name: "Ethereum",
    token: "USDC",
    contractAddress: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    decimals: 6,
    rpcUrl: "https://eth.llamarpc.com",
    explorerUrl: "https://etherscan.io",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#627EEA",
    defillamaId: "usd-coin",
  },
  {
    id: "arbitrum-usdc",
    name: "Arbitrum",
    token: "USDC",
    contractAddress: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
    decimals: 6,
    rpcUrl: "https://arb1.arbitrum.io/rpc",
    explorerUrl: "https://arbiscan.io",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#12AAFF",
  },
  {
    id: "avalanche-usdc",
    name: "Avalanche",
    token: "USDC",
    contractAddress: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
    decimals: 6,
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    explorerUrl: "https://snowscan.xyz",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#E84142",
  },
  {
    id: "base-usdc",
    name: "Base",
    token: "USDC",
    contractAddress: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    decimals: 6,
    rpcUrl: "https://mainnet.base.org",
    explorerUrl: "https://basescan.org",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#0052FF",
  },
  {
    id: "celo-usdc",
    name: "Celo",
    token: "USDC",
    contractAddress: "0xcebA9300f2b948710d2653dD7B07f33A8B32118C",
    decimals: 6,
    rpcUrl: "https://forno.celo.org",
    explorerUrl: "https://celoscan.io",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#FCFF52",
  },
  {
    id: "codex-usdc",
    name: "Codex",
    token: "USDC",
    contractAddress: "0xd996633a415985DBd7D6D12f4A4343E31f5037cf",
    decimals: 6,
    rpcUrl: "https://rpc.codex.xyz",
    explorerUrl: "https://explorer.codex.xyz",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#7B3FE4",
  },
  {
    id: "hyperevm-usdc",
    name: "HyperEVM",
    token: "USDC",
    contractAddress: "0xb88339CB7199b77E23DB6E890353E22632Ba630f",
    decimals: 6,
    rpcUrl: "https://rpc.hyperliquid.xyz/evm",
    explorerUrl: "https://purrsec.com/hyperliquid",
    explorerAddressPath: "/address/",
    chainType: "evm",
    color: "#77E66A",
  },
  {
    id: "ink-usdc",
    name: "Ink",
    token: "USDC",
    contractAddress: "0x2D270e6886d130D724215A266106e6832161EAEd",
    decimals: 6,
    rpcUrl: "https://rpc-gel.inkonchain.com",
    explorerUrl: "https://explorer.inkonchain.com",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#7B61FF",
  },
  {
    id: "linea-usdc",
    name: "Linea",
    token: "USDC",
    contractAddress: "0x176211869cA2b568f2A7D4EE941E073a821EE1ff",
    decimals: 6,
    rpcUrl: "https://rpc.linea.build",
    explorerUrl: "https://lineascan.build",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#61DFFF",
  },
  {
    id: "monad-usdc",
    name: "Monad",
    token: "USDC",
    contractAddress: "0x754704Bc059F8C67012fEd69BC8A327a5aafb603",
    decimals: 6,
    rpcUrl: "https://rpc.monad.xyz",
    explorerUrl: "https://monadexplorer.com",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#836EF9",
  },
  {
    id: "optimism-usdc",
    name: "Optimism",
    token: "USDC",
    contractAddress: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85",
    decimals: 6,
    rpcUrl: "https://mainnet.optimism.io",
    explorerUrl: "https://optimistic.etherscan.io",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#FF0420",
  },
  {
    id: "plume-usdc",
    name: "Plume",
    token: "USDC",
    contractAddress: "0x222365EF19F7947e5484218551B56bb3965Aa7aF",
    decimals: 6,
    rpcUrl: "https://rpc.plume.org",
    explorerUrl: "https://explorer.plume.org",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#FF6B35",
  },
  {
    id: "polygon-usdc",
    name: "Polygon",
    token: "USDC",
    contractAddress: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359",
    decimals: 6,
    rpcUrl: "https://polygon-rpc.com",
    explorerUrl: "https://polygonscan.com",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#8247E5",
  },
  {
    id: "sei-usdc",
    name: "Sei",
    token: "USDC",
    contractAddress: "0xe15fC38F6D8c56aF07bbCBe3BAf5708A2Bf42392",
    decimals: 6,
    rpcUrl: "https://evm-rpc.sei-apis.com",
    explorerUrl: "https://seitrace.com",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#9B1C2E",
  },
  {
    id: "sonic-usdc",
    name: "Sonic",
    token: "USDC",
    contractAddress: "0x29219dd400f2Bf60E5a23d13Be72B486D4038894",
    decimals: 6,
    rpcUrl: "https://rpc.soniclabs.com",
    explorerUrl: "https://sonicscan.org",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#141414",
  },
  {
    id: "unichain-usdc",
    name: "Unichain",
    token: "USDC",
    contractAddress: "0x078D782b760474a361dDA0AF3839290b0EF57AD6",
    decimals: 6,
    rpcUrl: "https://mainnet.unichain.org",
    explorerUrl: "https://uniscan.xyz",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#FF007A",
  },
  {
    id: "worldchain-usdc",
    name: "World Chain",
    token: "USDC",
    contractAddress: "0x79A02482A880bCe3F13E09da970dC34dB4cD24D1",
    decimals: 6,
    rpcUrl: "https://worldchain-mainnet.g.alchemy.com/public",
    explorerUrl: "https://worldscan.org",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#191C20",
  },
  {
    id: "xdc-usdc",
    name: "XDC",
    token: "USDC",
    contractAddress: "0xfA2958CB79b0491CC627c1557F441eF849Ca8eb1",
    decimals: 6,
    rpcUrl: "https://rpc.xdc.org",
    explorerUrl: "https://xdcscan.io",
    explorerAddressPath: "/token/",
    chainType: "evm",
    color: "#1B72BA",
  },
  {
    id: "zksync-usdc",
    name: "ZKsync Era",
    token: "USDC",
    contractAddress: "0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4",
    decimals: 6,
    rpcUrl: "https://mainnet.era.zksync.io",
    explorerUrl: "https://explorer.zksync.io",
    explorerAddressPath: "/address/",
    chainType: "evm",
    color: "#4E529A",
  },
  // --- Non-EVM chains ---
  {
    id: "algorand-usdc",
    name: "Algorand",
    token: "USDC",
    contractAddress: "31566704",
    decimals: 6,
    rpcUrl: "https://mainnet-idx.4160.nodely.dev",
    explorerUrl: "https://allo.info",
    explorerAddressPath: "/asset/",
    chainType: "algorand",
    color: "#000000",
  },
  {
    id: "aptos-usdc",
    name: "Aptos",
    token: "USDC",
    contractAddress: "0xbae207659db88bea0cbead6da0ed00aac12edcdda169e591cd41c94180b46f3b",
    decimals: 6,
    rpcUrl: "https://fullnode.mainnet.aptoslabs.com/v1",
    explorerUrl: "https://explorer.aptoslabs.com",
    explorerAddressPath: "/account/",
    chainType: "aptos",
    color: "#4CA2FF",
  },
  {
    id: "hedera-usdc",
    name: "Hedera",
    token: "USDC",
    contractAddress: "0.0.456858",
    decimals: 6,
    rpcUrl: "https://mainnet.mirrornode.hedera.com",
    explorerUrl: "https://hashscan.io/mainnet",
    explorerAddressPath: "/token/",
    chainType: "hedera",
    color: "#8259EF",
  },
  {
    id: "near-usdc",
    name: "NEAR",
    token: "USDC",
    contractAddress: "17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1",
    decimals: 6,
    rpcUrl: "https://rpc.mainnet.near.org",
    explorerUrl: "https://nearblocks.io",
    explorerAddressPath: "/address/",
    chainType: "near",
    color: "#00C08B",
  },
  {
    id: "noble-usdc",
    name: "Noble",
    token: "USDC",
    contractAddress: "uusdc",
    decimals: 6,
    rpcUrl: "https://noble-api.polkachu.com",
    explorerUrl: "https://www.mintscan.io/noble",
    explorerAddressPath: "/assets/",
    chainType: "noble",
    color: "#3B82F6",
  },
  {
    id: "polkadot-usdc",
    name: "Polkadot",
    token: "USDC",
    contractAddress: "1337",
    decimals: 6,
    rpcUrl: "https://polkadot-asset-hub-public-sidecar.parity-chains.parity.io",
    explorerUrl: "https://assethub-polkadot.subscan.io",
    explorerAddressPath: "/assets/",
    chainType: "polkadot",
    color: "#E6007A",
  },
  {
    id: "solana-usdc",
    name: "Solana",
    token: "USDC",
    contractAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    decimals: 6,
    rpcUrl: "https://api.mainnet-beta.solana.com",
    explorerUrl: "https://solscan.io",
    explorerAddressPath: "/token/",
    chainType: "solana",
    color: "#9945FF",
  },
  {
    id: "starknet-usdc",
    name: "Starknet",
    token: "USDC",
    contractAddress: "0x033068f6539f8e6e6b131e6b2b814e6c34a5224bc66947c47dab9dfee93b35fb",
    decimals: 6,
    rpcUrl: "https://starknet-rpc.publicnode.com",
    explorerUrl: "https://starkscan.co",
    explorerAddressPath: "/token/",
    chainType: "starknet",
    color: "#EC796B",
  },
  {
    id: "stellar-usdc",
    name: "Stellar",
    token: "USDC",
    contractAddress: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
    decimals: 7,
    rpcUrl: "https://horizon.stellar.org",
    explorerUrl: "https://stellar.expert",
    explorerAddressPath: "/explorer/public/asset/USDC-",
    chainType: "stellar",
    color: "#333333",
  },
  {
    id: "sui-usdc",
    name: "Sui",
    token: "USDC",
    contractAddress: "0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC",
    decimals: 6,
    rpcUrl: "https://fullnode.mainnet.sui.io:443",
    explorerUrl: "https://suiscan.xyz",
    explorerAddressPath: "/mainnet/coin/",
    chainType: "sui",
    color: "#6FBCF0",
  },
  {
    id: "xrpl-usdc",
    name: "XRPL",
    token: "USDC",
    contractAddress: "rGm7WCVp9gb4jZHWTEtGUr4dd74z2XuWhE",
    decimals: 0,
    rpcUrl: "https://s1.ripple.com:51234",
    explorerUrl: "https://xrpscan.com",
    explorerAddressPath: "/account/",
    chainType: "xrpl",
    color: "#23292F",
  },
];

export const ALL_CHAINS = [...USDT_CHAINS, ...USDC_CHAINS];

export function getChainsByToken(token: "USDT" | "USDC"): ChainConfig[] {
  return token === "USDT" ? USDT_CHAINS : USDC_CHAINS;
}
